export enum BanquetsWebsocketEvent {
  CREATE_BANQUET = "CREATE_BANQUET",
  UPDATE_BANQUET = "UPDATE_BANQUET",
  REMOVE_BANQUET = "REMOVE_BANQUET",
  REMOVE_ALL_BANQUETS = "REMOVE_ALL_BANQUETS",
  REQUEST_BANQUETS_DATA = "REQUEST_BANQUETS_DATA",
  SEND_BANQUETS_DATA = "SEND_BANQUETS_DATA",
}
